// <auto-generated />
using System;
using BookingRoom.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookingRoom.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260414042300_init2")]
    partial class init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookingRoom.Entities.ChiTietDatPhong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DatPhongId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("GiaThucTe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PhongId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ThoiGianNhanPhongThucTe")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ThoiGianTraPhongThucTe")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DatPhongId");

                    b.HasIndex("PhongId");

                    b.ToTable("ChiTietDatPhongs");
                });

            modelBuilder.Entity("BookingRoom.Entities.ChinhSachGia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApDungChoThu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DenNgay")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DoUuTien")
                        .HasColumnType("integer");

                    b.Property<decimal>("GiaTriDieuChinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LoaiDieuChinh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LoaiPhongId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenChinhSach")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TuNgay")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("LoaiPhongId");

                    b.ToTable("ChinhSachGias");
                });

            modelBuilder.Entity("BookingRoom.Entities.ChucNang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("TenChucNang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("ChucNangs");
                });

            modelBuilder.Entity("BookingRoom.Entities.DatPhong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KhachHangId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayNhanPhongDuKien")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTraPhongDuKien")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.ToTable("DatPhongs");
                });

            modelBuilder.Entity("BookingRoom.Entities.DichVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LoaiDichVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("BookingRoom.Entities.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DatPhongId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LeTanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasColumnType("text");

                    b.Property<decimal>("SoTienDaThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienPhong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DatPhongId");

                    b.HasIndex("LeTanId");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("BookingRoom.Entities.KhachLuuTru", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CCCD_Passport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ChiTietDatPhongId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("QuocTich")
                        .HasColumnType("text");

                    b.Property<DateTime>("ThoiGianCheckIn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ThoiGianCheckOut")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietDatPhongId");

                    b.ToTable("KhachLuuTrus");
                });

            modelBuilder.Entity("BookingRoom.Entities.LeTan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MucLuongCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("LeTans");
                });

            modelBuilder.Entity("BookingRoom.Entities.LoaiPhong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("GiaCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<int>("SoNguoiToiDa")
                        .HasColumnType("integer");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("LoaiPhongs");
                });

            modelBuilder.Entity("BookingRoom.Entities.NguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DefaultRole")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProfileCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("QueQuan")
                        .HasColumnType("text");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("text");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("BookingRoom.Entities.NguoiDungVaiTro", b =>
                {
                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VaiTroId")
                        .HasColumnType("uuid");

                    b.HasKey("NguoiDungId", "VaiTroId");

                    b.HasIndex("VaiTroId");

                    b.ToTable("NguoiDungVaiTros");
                });

            modelBuilder.Entity("BookingRoom.Entities.Phong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LoaiPhongId")
                        .HasColumnType("uuid");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Tang")
                        .HasColumnType("integer");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("LoaiPhongId");

                    b.HasIndex("SoPhong")
                        .IsUnique();

                    b.ToTable("Phongs");
                });

            modelBuilder.Entity("BookingRoom.Entities.Quyen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChucNangId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<string>("GiaTriQuyen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChucNangId");

                    b.ToTable("Quyens");
                });

            modelBuilder.Entity("BookingRoom.Entities.SuDungDichVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChiTietDatPhongId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DichVuId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietDatPhongId");

                    b.HasIndex("DichVuId");

                    b.ToTable("SuDungDichVus");
                });

            modelBuilder.Entity("BookingRoom.Entities.TaiSanHuHai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChiTietDatPhongId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MoTaThietHai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PhiDenBu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ThietBiPhongId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TrucBuongId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietDatPhongId");

                    b.HasIndex("ThietBiPhongId");

                    b.HasIndex("TrucBuongId");

                    b.ToTable("TaiSanHuHais");
                });

            modelBuilder.Entity("BookingRoom.Entities.ThietBi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TongSoLuong")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("ThietBis");
                });

            modelBuilder.Entity("BookingRoom.Entities.ThietBiPhong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PhongId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ThietBiId")
                        .HasColumnType("uuid");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("PhongId");

                    b.HasIndex("ThietBiId");

                    b.ToTable("ThietBiPhongs");
                });

            modelBuilder.Entity("BookingRoom.Entities.TrucBuong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("KhuVucPhuTrach")
                        .HasColumnType("text");

                    b.Property<decimal?>("MucLuongCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("TrucBuongs");
                });

            modelBuilder.Entity("BookingRoom.Entities.VaiTro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("VaiTros");
                });

            modelBuilder.Entity("BookingRoom.Entities.VaiTroQuyen", b =>
                {
                    b.Property<Guid>("VaiTroId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuyenId")
                        .HasColumnType("uuid");

                    b.HasKey("VaiTroId", "QuyenId");

                    b.HasIndex("QuyenId");

                    b.ToTable("VaiTroQuyens");
                });

            modelBuilder.Entity("KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CccdPassport")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuocTich")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("BookingRoom.Entities.ChiTietDatPhong", b =>
                {
                    b.HasOne("BookingRoom.Entities.DatPhong", "DatPhong")
                        .WithMany("ChiTietDatPhongs")
                        .HasForeignKey("DatPhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingRoom.Entities.Phong", "Phong")
                        .WithMany("ChiTietDatPhongs")
                        .HasForeignKey("PhongId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DatPhong");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("BookingRoom.Entities.ChinhSachGia", b =>
                {
                    b.HasOne("BookingRoom.Entities.LoaiPhong", "LoaiPhong")
                        .WithMany("ChinhSachGias")
                        .HasForeignKey("LoaiPhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("BookingRoom.Entities.DatPhong", b =>
                {
                    b.HasOne("KhachHang", "KhachHang")
                        .WithMany("DatPhongs")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("BookingRoom.Entities.HoaDon", b =>
                {
                    b.HasOne("BookingRoom.Entities.DatPhong", "DatPhong")
                        .WithMany("HoaDons")
                        .HasForeignKey("DatPhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingRoom.Entities.LeTan", "LeTan")
                        .WithMany("HoaDons")
                        .HasForeignKey("LeTanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DatPhong");

                    b.Navigation("LeTan");
                });

            modelBuilder.Entity("BookingRoom.Entities.KhachLuuTru", b =>
                {
                    b.HasOne("BookingRoom.Entities.ChiTietDatPhong", "ChiTietDatPhong")
                        .WithMany("KhachLuuTrus")
                        .HasForeignKey("ChiTietDatPhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietDatPhong");
                });

            modelBuilder.Entity("BookingRoom.Entities.LeTan", b =>
                {
                    b.HasOne("BookingRoom.Entities.NguoiDung", "NguoiDung")
                        .WithOne("LeTan")
                        .HasForeignKey("BookingRoom.Entities.LeTan", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("BookingRoom.Entities.NguoiDungVaiTro", b =>
                {
                    b.HasOne("BookingRoom.Entities.NguoiDung", "NguoiDung")
                        .WithMany("NguoiDungVaiTros")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingRoom.Entities.VaiTro", "VaiTro")
                        .WithMany("NguoiDungVaiTros")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("BookingRoom.Entities.Phong", b =>
                {
                    b.HasOne("BookingRoom.Entities.LoaiPhong", "LoaiPhong")
                        .WithMany("Phongs")
                        .HasForeignKey("LoaiPhongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("BookingRoom.Entities.Quyen", b =>
                {
                    b.HasOne("BookingRoom.Entities.ChucNang", "ChucNang")
                        .WithMany("Quyens")
                        .HasForeignKey("ChucNangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucNang");
                });

            modelBuilder.Entity("BookingRoom.Entities.SuDungDichVu", b =>
                {
                    b.HasOne("BookingRoom.Entities.ChiTietDatPhong", "ChiTietDatPhong")
                        .WithMany("SuDungDichVus")
                        .HasForeignKey("ChiTietDatPhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingRoom.Entities.DichVu", "DichVu")
                        .WithMany("SuDungDichVus")
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChiTietDatPhong");

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("BookingRoom.Entities.TaiSanHuHai", b =>
                {
                    b.HasOne("BookingRoom.Entities.ChiTietDatPhong", "ChiTietDatPhong")
                        .WithMany("TaiSanHuHais")
                        .HasForeignKey("ChiTietDatPhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingRoom.Entities.ThietBiPhong", "ThietBiPhong")
                        .WithMany("TaiSanHuHais")
                        .HasForeignKey("ThietBiPhongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookingRoom.Entities.TrucBuong", "TrucBuong")
                        .WithMany("TaiSanHuHais")
                        .HasForeignKey("TrucBuongId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChiTietDatPhong");

                    b.Navigation("ThietBiPhong");

                    b.Navigation("TrucBuong");
                });

            modelBuilder.Entity("BookingRoom.Entities.ThietBiPhong", b =>
                {
                    b.HasOne("BookingRoom.Entities.Phong", "Phong")
                        .WithMany("ThietBiPhongs")
                        .HasForeignKey("PhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingRoom.Entities.ThietBi", "ThietBi")
                        .WithMany("ThietBiPhongs")
                        .HasForeignKey("ThietBiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Phong");

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("BookingRoom.Entities.TrucBuong", b =>
                {
                    b.HasOne("BookingRoom.Entities.NguoiDung", "NguoiDung")
                        .WithOne("TrucBuong")
                        .HasForeignKey("BookingRoom.Entities.TrucBuong", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("BookingRoom.Entities.VaiTroQuyen", b =>
                {
                    b.HasOne("BookingRoom.Entities.Quyen", "Quyen")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("QuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingRoom.Entities.VaiTro", "VaiTro")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quyen");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("KhachHang", b =>
                {
                    b.HasOne("BookingRoom.Entities.NguoiDung", "NguoiDung")
                        .WithOne("KhachHang")
                        .HasForeignKey("KhachHang", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("BookingRoom.Entities.ChiTietDatPhong", b =>
                {
                    b.Navigation("KhachLuuTrus");

                    b.Navigation("SuDungDichVus");

                    b.Navigation("TaiSanHuHais");
                });

            modelBuilder.Entity("BookingRoom.Entities.ChucNang", b =>
                {
                    b.Navigation("Quyens");
                });

            modelBuilder.Entity("BookingRoom.Entities.DatPhong", b =>
                {
                    b.Navigation("ChiTietDatPhongs");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("BookingRoom.Entities.DichVu", b =>
                {
                    b.Navigation("SuDungDichVus");
                });

            modelBuilder.Entity("BookingRoom.Entities.LeTan", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("BookingRoom.Entities.LoaiPhong", b =>
                {
                    b.Navigation("ChinhSachGias");

                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("BookingRoom.Entities.NguoiDung", b =>
                {
                    b.Navigation("KhachHang");

                    b.Navigation("LeTan");

                    b.Navigation("NguoiDungVaiTros");

                    b.Navigation("TrucBuong");
                });

            modelBuilder.Entity("BookingRoom.Entities.Phong", b =>
                {
                    b.Navigation("ChiTietDatPhongs");

                    b.Navigation("ThietBiPhongs");
                });

            modelBuilder.Entity("BookingRoom.Entities.Quyen", b =>
                {
                    b.Navigation("VaiTroQuyens");
                });

            modelBuilder.Entity("BookingRoom.Entities.ThietBi", b =>
                {
                    b.Navigation("ThietBiPhongs");
                });

            modelBuilder.Entity("BookingRoom.Entities.ThietBiPhong", b =>
                {
                    b.Navigation("TaiSanHuHais");
                });

            modelBuilder.Entity("BookingRoom.Entities.TrucBuong", b =>
                {
                    b.Navigation("TaiSanHuHais");
                });

            modelBuilder.Entity("BookingRoom.Entities.VaiTro", b =>
                {
                    b.Navigation("NguoiDungVaiTros");

                    b.Navigation("VaiTroQuyens");
                });

            modelBuilder.Entity("KhachHang", b =>
                {
                    b.Navigation("DatPhongs");
                });
#pragma warning restore 612, 618
        }
    }
}
