// <auto-generated />
using System;
using BookingRoom.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookingRoom.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260411093307_Permission")]
    partial class Permission
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookingRoom.Entities.ChucNang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("TenChucNang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ChucNangs");
                });

            modelBuilder.Entity("BookingRoom.Entities.LeTan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MucLuongCoBan")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("LeTans");
                });

            modelBuilder.Entity("BookingRoom.Entities.NguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultRole")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProfileCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QueQuan")
                        .HasColumnType("text");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("text");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("BookingRoom.Entities.NguoiDungVaiTro", b =>
                {
                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaiTroId")
                        .HasColumnType("uuid");

                    b.HasKey("NguoiDungId", "VaiTroId");

                    b.HasIndex("VaiTroId");

                    b.ToTable("NguoiDungVaiTros");
                });

            modelBuilder.Entity("BookingRoom.Entities.Quyen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChucNangId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<string>("GiaTriQuyen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChucNangId");

                    b.ToTable("Quyens");
                });

            modelBuilder.Entity("BookingRoom.Entities.TrucBuong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("KhuVucPhuTrach")
                        .HasColumnType("text");

                    b.Property<decimal?>("MucLuongCoBan")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("TrucBuongs");
                });

            modelBuilder.Entity("BookingRoom.Entities.VaiTro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("VaiTros");
                });

            modelBuilder.Entity("BookingRoom.Entities.VaiTroQuyen", b =>
                {
                    b.Property<Guid>("VaiTroId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuyenId")
                        .HasColumnType("uuid");

                    b.HasKey("VaiTroId", "QuyenId");

                    b.HasIndex("QuyenId");

                    b.ToTable("VaiTroQuyens");
                });

            modelBuilder.Entity("KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CccdPassport")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuocTich")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("BookingRoom.Entities.LeTan", b =>
                {
                    b.HasOne("BookingRoom.Entities.NguoiDung", "NguoiDung")
                        .WithOne("LeTan")
                        .HasForeignKey("BookingRoom.Entities.LeTan", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("BookingRoom.Entities.NguoiDungVaiTro", b =>
                {
                    b.HasOne("BookingRoom.Entities.NguoiDung", "NguoiDung")
                        .WithMany("NguoiDungVaiTros")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingRoom.Entities.VaiTro", "VaiTro")
                        .WithMany("NguoiDungVaiTros")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("BookingRoom.Entities.Quyen", b =>
                {
                    b.HasOne("BookingRoom.Entities.ChucNang", "ChucNang")
                        .WithMany("Quyens")
                        .HasForeignKey("ChucNangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucNang");
                });

            modelBuilder.Entity("BookingRoom.Entities.TrucBuong", b =>
                {
                    b.HasOne("BookingRoom.Entities.NguoiDung", "NguoiDung")
                        .WithOne("TrucBuong")
                        .HasForeignKey("BookingRoom.Entities.TrucBuong", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("BookingRoom.Entities.VaiTroQuyen", b =>
                {
                    b.HasOne("BookingRoom.Entities.Quyen", "Quyen")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("QuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingRoom.Entities.VaiTro", "VaiTro")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quyen");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("KhachHang", b =>
                {
                    b.HasOne("BookingRoom.Entities.NguoiDung", "NguoiDung")
                        .WithOne("KhachHang")
                        .HasForeignKey("KhachHang", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("BookingRoom.Entities.ChucNang", b =>
                {
                    b.Navigation("Quyens");
                });

            modelBuilder.Entity("BookingRoom.Entities.NguoiDung", b =>
                {
                    b.Navigation("KhachHang");

                    b.Navigation("LeTan");

                    b.Navigation("NguoiDungVaiTros");

                    b.Navigation("TrucBuong");
                });

            modelBuilder.Entity("BookingRoom.Entities.Quyen", b =>
                {
                    b.Navigation("VaiTroQuyens");
                });

            modelBuilder.Entity("BookingRoom.Entities.VaiTro", b =>
                {
                    b.Navigation("NguoiDungVaiTros");

                    b.Navigation("VaiTroQuyens");
                });
#pragma warning restore 612, 618
        }
    }
}
